### PR TITLE
Memory leak in gzip compress and decompress

### PR DESCRIPTION
**Pull request by saikat**
Hi Ivan,

Have been using your fork of node-compress for a while in development and really loving it - a great improvement over the original waveto version, and loving the streaming API!

Just noticed though that there might be a memory leak in the library.  The pull request is just for the test demonstrating this (feel free to put it in a place that makes more sense than "mem_test").  Unfortunately, C++ knowledge is limited, so it may take me a while to figure out how to actually plug the leak, but I'm trying to take a shot at it tonight.  Hope this helps!

-- Saikat

### CODE REVIEW

**Comment by egorich239** [comment]
Saikat,

Thanks for your interest in node-compress. Although I will have some spare time at Sunday, most likely I won't have much time to investigate this either at weekend as well as next week, so I'd appreciate your help.

Thanks,
Ivan.

**Comment by saikat** [comment]
Thanks for the response Ivan, I'll try to investigate.

**Comment by saikat** [comment]
Also, it seems like the issue related to this pull request (as well as the pull request itself) got closed.  It seems useful to have these tests in the node-compress code base to make sure leaks don't appear in the future?

**Comment by egorich239** [comment]
These tests actually leak memory, but on JS side. You create a chain of 200 closures, each containing at least compressedText variable. So, it doesn't show whether C++ leaks, it leaks on JS side.

**Comment by saikat** [comment]
The memory might leak during the test run, but there is a 10 second pause at the end of the tests during which the GC should kick in and clean up any memory.  The closures, at that point, should be out of scope since this happens in a setTimeout and compressed text only exists within the scope of those closures.  Am I mistaken about this?  

Additionally, I've tried using node-compress in a node-server doing a bunch of hits and it is definitely leaking memory.  http://github.com/saikat/node-gzip, which is a fork of waveto's original code but with some leaks plugged, does not leak in this same environment.

I also don't think I am the only one having this problem.  I talked to a few people in IRC having memory leak issues with Connect's gzip middleware as it uses node-compress.

**Comment by egorich239** [comment]
Closed.

**Pull request closed without merging**
